# Generated by Django 6.0.5 on 2026-06-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='user',
        ),
    ]
