# Generated by Django 6.0.5 on 2026-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
